CREATE TABLE Orders (
  ORDER_ID     BIGINT       PRIMARY KEY,
  ORDER_TYPE   VARCHAR2(20) NOT NULL,
  INVENTORY_ID BIGINT       NOT NULL,
  ITEM_COUNT   INT          NOT NULL
);

INSERT INTO Orders VALUES (1, 'Software', 1000, 1);
INSERT INTO Orders VALUES (2, 'Hardware', 2000, 2);